
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% Run through all examples and generate data
%
% THIS MAY TAKE A LONG TIME
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

s = input('this may take a few hours, continue? (y/n): ','s');

if (s == 'y' || s == 'Y')

  orig_state = warning;
  warning('off','all');
  
  fprintf('generating data for periodic example ...')
  sensor_periodic
  fprintf('generating data for hidden dynamics example ...')
  sensor_hidden_dynamics
  fprintf('generating data for periodic example (uncertain times) ...')
  sample_periodic

  fprintf('data generation complete ...')
  fprintf('figures may now be generated by running the *_figs.m files ...')

  warning(orig_state);
  
end
